name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-2-chocolatine-iyad.djibril-moriba.git"
  EXECUTABLES: "mysh,directory1/executableA,directory2/executableB"

jobs:
  check_coding_style:
    run-on: unbutu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: run-commande
          run: check.sh $(pwd) $(pwd)
        - name: display-it
          run: cat $(pwd)/coding-style-report.log